# Main Colors
unrecognized_file: '#ECEFF4'
recognized_file:   '#D8DEE9'
dir:               '#5E81AC'

# Link
dead_link: '#B48EAD'
link:      '#8FBCBB'

# special files
socket:    green
blockdev:  green
chardev:   green

# Access Modes
write:     '#EBCB8B'
read:      '#A3BE8C'
exec:      '#D08770'
no_access: '#BF616A'

# Age
#day_old:     '#93B7DB'
#hour_old:    '#ABD5FF'
day_old:     '#81A1C1'
hour_old:    '#81A1C1'
no_modifier: '#81A1C1'

# File Size
file_large:  '#67929E'
file_medium: '#77AAB8'
file_small:  '#88C0D0'

# Random
report: white
user:   '#5E81AC'
tree:   cyan
empty:  yellow
error:  red
normal: '#D8DEE9'

# Git
addition:     chartreuse
modification: darkkhaki
deletion:     darkred
untracked:    darkorange
unchanged:    forestgreen
