# Taps
tap 'homebrew/cask-fonts'

# Install tools
brew 'ack'
brew 'ansible'
brew 'asciinema'
brew 'brew-cask-completion'
brew 'cocoapods'
brew 'cowsay'
brew 'csshx'
brew 'ctop'
brew 'curl'
brew 'derailed/k9s/k9s'
brew 'docker-clean'
brew 'fasd'
brew 'fortune'
brew 'git'
bree 'github/gh/gh'
brew 'grep'
brew 'httpie'
brew 'htop'
brew 'kubernetes-cli'
brew 'kubectx'
brew 'kubeseal'
brew 'int128/kubelogin/kubelogin'
brew 'krew'
brew 'less'
brew 'lolcat'
brew 'mackup'
brew 'mas'
brew 'mycli'
brew 'n'
brew 'nano'
brew 'neofetch'
brew 'no-more-secrets'
brew 'prettyping'
brew 'screen'
brew 'speedtest-cli'
brew 'sqlite'
brew 'telnet'
brew 'the_silver_searcher'
brew 'watch'
brew 'wget'
brew 'vim'
brew 'youtube-dl'

# Applications
cask 'alfred'
cask 'bartender'
cask 'cakebrew'
cask 'docker'
cask 'evernote'
cask 'firefox'
cask 'google-chrome'
cask 'insomnia'
cask 'iterm2'
cask 'itsycal'
cask 'microsoft-teams'
cask 'qlcolorcode'
cask 'qlstephen'
cask 'qlmarkdown' 
cask 'quicklook-json'
cask 'qlprettypatch'
cask 'quicklook-csv'
cask 'sequel-pro'
cask 'spotify'
cask 'spotmenu'
cask 'suspicious-package'
cask 'virtualbox'
cask 'virtualbox-extension-pack'
cask 'vagrant'
cask 'viscosity'
cask 'vlc'
cask 'WebPQuickLook'

# Fonts
cask 'font-inconsolata'
cask 'font-inconsolata-dz-for-powerline'
cask 'font-lato'
cask 'font-open-sans'
cask 'font-open-sans-condensed'
cask 'font-source-code-pro'
cask 'font-source-sans-pro'
cask 'font-source-serif-pro'
cask 'font-roboto'
cask 'font-roboto-condensed'
cask 'font-roboto-mono'
cask 'font-comfortaa'
cask 'font-hack'
cask 'font-montserrat'
cask 'font-victor-mono'
cask 'font-3270-nerd-font-mono'

# App store
mas "BetterSnapTool", id: 417375580
mas "The Unarchiver", id: 425424353
mas "Slack", id: 803453959
mas "Trello", id: 1278508951
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Keynote", id: 409183694
mas "CopyClip", id: 595191960
mas "WireGuard", id: 1451685025
mas "Xcode", id: 497799835
