#!/bin/bash

# Change dir to HOME
cd $HOME

# Hide "last login" line when starting a new terminal session
touch $HOME/.hushlogin

echo ''
echo 'Install homebrew'
echo '----------------'
sudo rm -rf /usr/local/Cellar /usr/local/.git && brew cleanup
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

brew update

if [[ ! "$DISABLE_CLI" == "true" ]]; then
    source $HOME/.dotfiles/install/cli.sh
fi

if [[ ! "$DISABLE_GIT" == "true" ]]; then
    source $HOME/.dotfiles/install/git.sh
fi

if [[ ! "$DISABLE_SVN" == "true" ]]; then
    source $HOME/.dotfiles/install/svn.sh
fi

if [[ ! "$DISABLE_SHELL" == "true" ]]; then
    source $HOME/.dotfiles/install/shell.sh
fi

if [[ ! "$DISABLE_VIM" == "true" ]]; then
    source $HOME/.dotfiles/install/vim.sh
fi

if [[ ! "$DISABLE_CLOUD" == "true" ]]; then
    source $HOME/.dotfiles/install/cloud.sh
fi

if [[ ! "$DISABLE_KUBERNETES" == "true" ]]; then
    source $HOME/.dotfiles/install/kube.sh
fi

if [[ ! "$DISABLE_DOCKER" == "true" ]]; then
    source $HOME/.dotfiles/install/docker.sh
fi

if [[ ! "$DISABLE_PHP" == "true" ]]; then
    source $HOME/.dotfiles/install/php.sh
fi

if [[ ! "$DISABLE_NODE" == "true" ]]; then
    source $HOME/.dotfiles/install/node.sh
fi

if [[ ! "$DISABLE_VIRTUALISATION" == "true" ]]; then
    source $HOME/.dotfiles/install/gui.sh
fi

if [[ ! "$DISABLE_GUI" == "true" ]]; then
    source $HOME/.dotfiles/install/gui.sh
fi

if [[ ! "$DISABLE_DATABASE" == "true" ]]; then
    source $HOME/.dotfiles/install/database.sh
fi

if [[ ! "$DISABLE_MEDIA" == "true" ]]; then
    source $HOME/.dotfiles/install/media.sh
fi

if [[ ! "$DISABLE_BROWSER" == "true" ]]; then
    source $HOME/.dotfiles/install/browser.sh
fi

if [[ ! "$DISABLE_MESSENGER" == "true" ]]; then
    source $HOME/.dotfiles/install/messenger.sh
fi

if [[ ! "$DISABLE_EDITOR" == "true" ]]; then
    source $HOME/.dotfiles/install/editor.sh
fi

if [[ ! "$DISABLE_MAS" == "true" ]]; then
    source $HOME/.dotfiles/install/mas.sh
fi

if [[ ! "$DISABLE_QUICKLOOk" == "true" ]]; then
    source $HOME/.dotfiles/install/quicklook.sh
fi

if [[ ! "$DISABLE_FONT" == "true" ]]; then
    source $HOME/.dotfiles/install/font.sh
fi

if [[ ! "$DISABLE_MACKUP" == "true" ]]; then
    echo ''
    echo 'Install Mackup'
    echo '--------------'
    brew install mackup
    rm $HOME/.mackup.cfg
    ln -s $HOME/.dotfiles/macos/mackup.cfg $HOME/.mackup.cfg

    if [ -d "$HOME/Dropbox/Mackup/" ]; then
        mackup restore --force
    fi
fi

echo ''
echo ''
echo '+++++++++++++++++++++++++++++++'
echo '+          All done!          +'
echo '+++++++++++++++++++++++++++++++'
echo ''
echo ''
echo 'Some optional tidbits'

chmod +x $HOME/.dotfiles/macos/set-defaults.sh
chmod +x $HOME/.dotfiles/macos/unset-defaults.sh
echo '1. Set some sensible macos defaults by running: $HOME/.dotfiles/macos/set-defaults.sh'
echo '2. Make a .dotfiles-custom/shell/.aliases for your custom commands'
echo '3. Download themes from nordtheme.com for matching styling'

echo '+++++++++++++++++++++++++++++++'
echo '+++++++++++++++++++++++++++++++'
