syntax enable

set encoding=UTF-8

set number
set mouse-=a
set bs=2

set nocompatible
set hidden
set termguicolors
set noshowmode
set laststatus=2

call plug#begin()
Plug 'itchyny/lightline.vim'
Plug 'catppuccin/vim', { 'as': 'catppuccin' }
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
Plug 'andrewstuart/vim-kubernetes'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'tpope/vim-fugitive'
Plug 'vim-utils/vim-man'
Plug 'mbbill/undotree'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'dense-analysis/ale'
Plug 'OmniSharp/omnisharp-vim'
Plug 'sirver/UltiSnips'
Plug 'honza/vim-snippets'
Plug 'mattn/emmet-vim'
Plug 'preservim/nerdtree'
Plug 'xuyuanp/nerdtree-git-plugin'
Plug 'ryanoasis/vim-devicons'
Plug 'godlygeek/tabular'
Plug 'ap/vim-buftabline'
Plug 'sheerun/vim-polyglot'
call plug#end()

"NERDTree
let NERDTreeMinimalUI = 1
let NERDTreeShowHidden = 1
let NERDTreeDirArrows = 1
let NERDTreeQuitOnOpen = 1
"Leader is \
"let mapleader = ','
nnoremap <Leader>m :NERDTreeToggle<CR>
nnoremap <silent> <Leader>n :NERDTreeFind<CR>

nnoremap <C-S-n> :bnext<CR>
nnoremap <C-S-b> :bprev<CR>

colorscheme catppuccin_frappe
let g:lightline = {'colorscheme': 'catppuccin_frappe'}
