import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin/catppuccin-mocha.toml"
  # "~/.config/alacritty/catppuccin/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin/catppuccin-latte.toml"
]

[font]
size = 12.0

[font.bold]
family = "Maple Mono NF"
style = "Bold"

[font.italic]
family = "Maple Mono NF"
style = "Light italic"

[font.normal]
family = "Maple Mono NF"
style = "Light"

[shell]
args = ["--login"]
program = "/bin/zsh"

[window]
opacity = 0.9

[window.padding]
x = 4
y = 4
