import:
  - ~/.config/alacritty/catppuccin/catppuccin-frappe.yml
window:
  padding:
    x: 4
    y: 4
  opacity: 0.9
font:
  normal:
    family: Maple Mono NF
    style: light
  bold:
    family: Maple Mono NF
    style: Bold
  italic:
    family: Maple Mono NF
    style: Light italic
  size: 12.0
shell:
  program: /bin/zsh
  args:
    - --login
