#!/usr/bin/env bash

export HOME=/Users/$(whoami)
export PATH=$HOME/.bin:$PATH

source $HOME/.dotfiles/jobs/common.sh
source $HOME/.dotfiles/shell/logging.sh

ANYFAIL=false
function anyfail() {
    log_task_fail
    ANYFAIL=true
}

log_task "Daily job $(date '+%Y-%m-%d %T')"

echo "daily: brew upgrade" >> $HOME/.dotfiles/jobs/job.log
log_task "brew upgrade" \
    && brew update >> $HOME/.dotfiles/jobs/job.log 2>&1 \
    && brew upgrade >> $HOME/.dotfiles/jobs/job.log 2>&1 \
    && brew cleanup >> $HOME/.dotfiles/jobs/job.log 2>&1 \
    && log_task_success \
    || anyfail
echo "" >> $HOME/.dotfiles/jobs/job.log

echo "daily: update-repo (.dotfiles)" >> $HOME/.dotfiles/jobs/job.log
log_task "update-repo dotfiles" \
    && $HOME/.dotfiles/bin/update-repos $HOME/.dotfiles >> $HOME/.dotfiles/jobs/job.log 2>&1 \
    && log_task_success \
    || anyfail
echo "" >> $HOME/.dotfiles/jobs/job.log

echo "daily: update-repos (Developer)" >> $HOME/.dotfiles/jobs/job.log
log_task "update-repos Developer" \
    && $HOME/.dotfiles/bin/update-repos $HOME/Developer >> $HOME/.dotfiles/jobs/job.log 2>&1 \
    && log_task_success \
    || anyfail
echo "" >> $HOME/.dotfiles/jobs/job.log

if [ "$ANYFAIL" = true ]; then
    log_task_fail
    log_warn "Check $HOME/.dotfiles/jobs/job.log for more information"
    exit 1
else
    log_task_success
    rm -f $HOME/.dotfiles/jobs/job.log
    date "+%s" > $HOME/.dotfiles/jobs/.daily
    exit 0
fi
