#!/usr/bin/env bash

source $HOME/.dotfiles/shell/logging.sh

ANYFAIL=false
function anyfail() {
    log_task_fail
    ANYFAIL=true
}

log_task "Daily job"

echo "brew upgrade" >> $HOME/.dotfiles/jobs/daily-log
log_task "brew upgrade" \
    && brew update &>> $HOME/.dotfiles/jobs/daily-log \
    && brew upgrade &>> $HOME/.dotfiles/jobs/daily-log \
    && brew cleanup &>> $HOME/.dotfiles/jobs/daily-log \
    && log_task_success \
    || anyfail
echo "" >> $HOME/.dotfiles/jobs/daily-log

echo "update ~/.tooling-devops-cli" >> $HOME/.dotfiles/jobs/weekly-log
log_task "update ~/.tooling-devops-cli" \
    && $HOME/.dotfiles/bin/update-repos $HOME/.tooling-devops-cli &>> $HOME/.dotfiles/jobs/weekly-log \
    && log_task_success \
    || anyfail

if [ "$ANYFAIL" = true ]; then
    log_task_fail
    log_warn "Check $HOME/.dotfiles/jobs/daily-log for more information"
    exit 1
else
    log_task_success
    mv $HOME/.dotfiles/jobs/daily-log $HOME/.Trash/
    exit 0
fi