#!/usr/bin/env bash

export HOME=/Users/$(whoami)
export PATH=$HOME/.bin:$PATH

source $HOME/.dotfiles/jobs/common.sh
source $HOME/.dotfiles/shell/logging.sh

ANYFAIL=false
function anyfail() {
    log_task_fail
    ANYFAIL=true
}

log_task "Weekly job $(date '+%Y-%m-%d %T')"

echo "weekly: brew cask upgrade" >> $HOME/.dotfiles/jobs/job.log
log_task "brew cask upgrade" \
    && brew update >> $HOME/.dotfiles/jobs/job.log 2>&1 \
    && brew upgrade --cask --greedy >> $HOME/.dotfiles/jobs/job.log 2>&1 \
    && brew cleanup >> $HOME/.dotfiles/jobs/job.log 2>&1 \
    && log_task_success \
    || anyfail
echo "" >> $HOME/.dotfiles/jobs/job.log

echo "weekly: tmux update" >> $HOME/.dotfiles/jobs/job.log
log_task "tmux update" \
    && bash $HOME/.tmux/plugins/tpm/bin/install_plugins >> $HOME/.dotfiles/jobs/job.log 2>&1 \
    && bash $HOME/.tmux/plugins/tpm/bin/update_plugins "all" >> $HOME/.dotfiles/jobs/job.log 2>&1 \
    && bash $HOME/.tmux/plugins/tpm/bin/clean_plugins >> $HOME/.dotfiles/jobs/job.log 2>&1 \
    && log_task_success \
    || anyfail
echo "" >> $HOME/.dotfiles/jobs/job.log

echo "weekly: vim update" >> $HOME/.dotfiles/jobs/job.log
log_task "vim update" \
    && git clone https://github.com/junegunn/vim-plug.git ~/.vim/_temp >> $HOME/.dotfiles/jobs/job.log 2>&1 \
    && rm -rf ~/.vim/autoload/plug.vim >> $HOME/.dotfiles/jobs/job.log 2>&1 \
    && cp ~/.vim/_temp/plug.vim ~/.vim/autoload/plug.vim >> $HOME/.dotfiles/jobs/job.log 2>&1 \
    && rm -rf ~/.vim/_temp >> $HOME/.dotfiles/jobs/job.log \
    && vim +PlugInstall +PlugUpdate +PlugUpgrade +PlugClean! +qa! >> $HOME/.dotfiles/jobs/job.log 2>&1 \
    && log_task_success \
    || anyfail
echo "" >> $HOME/.dotfiles/jobs/job.log

echo "weekly: update-repos (not Developer, not .dotfiles)" >> $HOME/.dotfiles/jobs/job.log
log_task "update-repos" \
    && update-repos $HOME "($HOME/Developer|$HOME/.dotfiles)" >> $HOME/.dotfiles/jobs/job.log 2>&1 \
    && log_task_success \
    || anyfail
echo "" >> $HOME/.dotfiles/jobs/job.log

if [ "$ANYFAIL" = true ]; then
    log_task_fail
    log_warn "Check $HOME/.dotfiles/jobs/job.log for more information"
    exit 1
else
    log_task_success
    rm -f $HOME/.dotfiles/jobs/job.log
    date "+%s" > $HOME/.dotfiles/jobs/.weekly
    exit 0
fi
