---
apiVersion: v1
kind: Pod
metadata:
  name: tmp-shell
spec:
  containers:
    - name: debian
      image: debian:bookworm-slim
      env:
        - name: TZ
          value: Europe/Berlin
      command: [/bin/sh]
      args: [-c, while true; do sleep 10; done]
      resources:
        limits:
          cpu: 1
          memory: 512Mi
        requests:
          cpu: 1
          memory: 512Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        privileged: false
        runAsNonRoot: true
        runAsUser: 1000
