---
apiVersion: v1
kind: Pod
metadata:
  name: tmp-shell
spec:
  containers:
    - name: psql
      image: alpine/psql
      env:
        - name: TZ
          value: Europe/Berlin
      command: [/bin/sh]
      args: [-c, while true; do sleep 10; done]
      resources:
        limits:
          cpu: 0.5
          memory: 128Mi
        requests:
          cpu: 0.5
          memory: 128Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        privileged: false
        runAsNonRoot: true
        runAsUser: 1000
